# Generated by Django 5.2.5 on 2025-11-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        db_column="idArriendo", primary_key=True, serialize=False
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, db_column="titulo", max_length=255, null=True
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, db_column="direccion", max_length=255, null=True
                    ),
                ),
                (
                    "download_date",
                    models.CharField(
                        blank=True, db_column="fechaDescarga", max_length=100, null=True
                    ),
                ),
                (
                    "correspondence_date",
                    models.CharField(
                        blank=True,
                        db_column="fechaCorrespondiente",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "region_comuna_id",
                    models.CharField(
                        blank=True,
                        db_column="idRegionComuna",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "comuna_id",
                    models.CharField(
                        blank=True, db_column="idComuna", max_length=100, null=True
                    ),
                ),
                (
                    "surface_total",
                    models.CharField(
                        blank=True,
                        db_column="superficieTotal",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "surface_useful",
                    models.CharField(
                        blank=True, db_column="superficieUtil", max_length=50, null=True
                    ),
                ),
                (
                    "surface_weighted",
                    models.CharField(
                        blank=True,
                        db_column="superficiePonderada",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "age_string",
                    models.CharField(
                        blank=True, db_column="antiguedad", max_length=100, null=True
                    ),
                ),
                (
                    "age_data",
                    models.CharField(
                        blank=True,
                        db_column="dataAntiguedad",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_furnished",
                    models.CharField(
                        blank=True, db_column="amoblado", max_length=50, null=True
                    ),
                ),
                (
                    "price_string",
                    models.CharField(
                        blank=True, db_column="precio", max_length=100, null=True
                    ),
                ),
                (
                    "uf_per_sqm",
                    models.CharField(
                        blank=True, db_column="uf_m2", max_length=100, null=True
                    ),
                ),
                (
                    "bedrooms",
                    models.CharField(
                        blank=True, db_column="habitaciones", max_length=50, null=True
                    ),
                ),
                (
                    "bathrooms",
                    models.CharField(
                        blank=True, db_column="banos", max_length=50, null=True
                    ),
                ),
                (
                    "parking_spots",
                    models.CharField(
                        blank=True,
                        db_column="estacionamientos",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "storage_units",
                    models.CharField(
                        blank=True, db_column="bodegas", max_length=50, null=True
                    ),
                ),
                (
                    "youtube_video_url",
                    models.CharField(
                        blank=True, db_column="url", max_length=500, null=True
                    ),
                ),
                ("latitude", models.CharField(blank=True, max_length=50, null=True)),
                ("longitude", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "uf_clp_value",
                    models.CharField(
                        blank=True, db_column="uf_clp", max_length=100, null=True
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True, db_column="moneda", max_length=50, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Propiedad de Arriendo",
                "verbose_name_plural": "Propiedades de Arriendo",
                "db_table": "arriendos",
                "managed": False,
            },
        ),
    ]
