# Generated by Django 5.2.5 on 2025-11-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Arriendo",
            fields=[
                (
                    "idArriendo",
                    models.IntegerField(
                        db_column="idArriendo", primary_key=True, serialize=False
                    ),
                ),
                (
                    "fechaDescarga",
                    models.DateTimeField(
                        blank=True, db_column="fechaDescarga", null=True
                    ),
                ),
                (
                    "fechaCorrespondiente",
                    models.DateTimeField(
                        blank=True, db_column="fechaCorrespondiente", null=True
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        blank=True, db_column="titulo", max_length=255, null=True
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True, db_column="direccion", max_length=255, null=True
                    ),
                ),
                (
                    "idRegionComuna",
                    models.IntegerField(
                        blank=True, db_column="idRegionComuna", null=True
                    ),
                ),
                (
                    "idComuna",
                    models.IntegerField(blank=True, db_column="idComuna", null=True),
                ),
                (
                    "superficieTotal",
                    models.CharField(
                        blank=True,
                        db_column="superficieTotal",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "superficieUtil",
                    models.CharField(
                        blank=True,
                        db_column="superficieUtil",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "superficiePonderada",
                    models.CharField(
                        blank=True,
                        db_column="superficiePonderada",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "antiguedad",
                    models.IntegerField(blank=True, db_column="antiguedad", null=True),
                ),
                (
                    "dataAntiguedad",
                    models.CharField(
                        blank=True, db_column="dataAntiguedad", max_length=15, null=True
                    ),
                ),
                (
                    "amoblado",
                    models.IntegerField(blank=True, db_column="amoblado", null=True),
                ),
                (
                    "precio",
                    models.IntegerField(blank=True, db_column="precio", null=True),
                ),
                (
                    "moneda",
                    models.CharField(
                        blank=True, db_column="moneda", max_length=2, null=True
                    ),
                ),
                ("uf_m2", models.FloatField(blank=True, db_column="uf_m2", null=True)),
                (
                    "habitaciones",
                    models.IntegerField(
                        blank=True, db_column="habitaciones", null=True
                    ),
                ),
                (
                    "banos",
                    models.IntegerField(blank=True, db_column="banos", null=True),
                ),
                (
                    "estacionamientos",
                    models.IntegerField(
                        blank=True, db_column="estacionamientos", null=True
                    ),
                ),
                (
                    "bodegas",
                    models.IntegerField(blank=True, db_column="bodegas", null=True),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, db_column="url", max_length=255, null=True
                    ),
                ),
                (
                    "latitud",
                    models.FloatField(blank=True, db_column="latitud", null=True),
                ),
                (
                    "longitud",
                    models.FloatField(blank=True, db_column="longitud", null=True),
                ),
                (
                    "uf_clp",
                    models.FloatField(blank=True, db_column="uf_clp", null=True),
                ),
            ],
            options={
                "verbose_name": "Arriendo",
                "verbose_name_plural": "Arriendos",
                "db_table": "arriendos",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ArriendoVenta",
            fields=[
                (
                    "idArriendoVenta",
                    models.IntegerField(
                        db_column="idArriendoVenta", primary_key=True, serialize=False
                    ),
                ),
                (
                    "distancia",
                    models.IntegerField(blank=True, db_column="distancia", null=True),
                ),
                (
                    "precioTransformadoLineal",
                    models.FloatField(
                        blank=True, db_column="precioTransformadoLineal", null=True
                    ),
                ),
                (
                    "precioTransformadoPonderado",
                    models.FloatField(
                        blank=True, db_column="precioTransformadoPonderado", null=True
                    ),
                ),
                (
                    "inversoDistanciaFactor",
                    models.FloatField(
                        blank=True, db_column="inversoDistanciaFactor", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Arriendo Venta",
                "verbose_name_plural": "Arriendos Ventas",
                "db_table": "arriendosventas",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "idVenta",
                    models.IntegerField(
                        db_column="idVenta", primary_key=True, serialize=False
                    ),
                ),
                (
                    "fechaDescarga",
                    models.DateTimeField(
                        blank=True, db_column="fechaDescarga", null=True
                    ),
                ),
                (
                    "fechaCorrespondiente",
                    models.DateTimeField(
                        blank=True, db_column="fechaCorrespondiente", null=True
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        blank=True, db_column="titulo", max_length=255, null=True
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True, db_column="direccion", max_length=255, null=True
                    ),
                ),
                (
                    "idRegionComuna",
                    models.IntegerField(
                        blank=True, db_column="idRegionComuna", null=True
                    ),
                ),
                (
                    "idComuna",
                    models.IntegerField(blank=True, db_column="idComuna", null=True),
                ),
                (
                    "disponibilidad",
                    models.CharField(
                        blank=True,
                        db_column="disponibilidad",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        blank=True, db_column="tipo", max_length=255, null=True
                    ),
                ),
                (
                    "superficieTotal",
                    models.CharField(
                        blank=True,
                        db_column="superficieTotal",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "superficieUtil",
                    models.CharField(
                        blank=True,
                        db_column="superficieUtil",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "superficiePonderada",
                    models.CharField(
                        blank=True,
                        db_column="superficiePonderada",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "antiguedad",
                    models.IntegerField(blank=True, db_column="antiguedad", null=True),
                ),
                (
                    "dataAntiguedad",
                    models.CharField(
                        blank=True, db_column="dataAntiguedad", max_length=15, null=True
                    ),
                ),
                (
                    "amoblado",
                    models.IntegerField(blank=True, db_column="amoblado", null=True),
                ),
                (
                    "precio",
                    models.IntegerField(blank=True, db_column="precio", null=True),
                ),
                (
                    "moneda",
                    models.CharField(
                        blank=True, db_column="moneda", max_length=2, null=True
                    ),
                ),
                ("uf_m2", models.FloatField(blank=True, db_column="uf_m2", null=True)),
                (
                    "habitaciones",
                    models.IntegerField(
                        blank=True, db_column="habitaciones", null=True
                    ),
                ),
                (
                    "banos",
                    models.IntegerField(blank=True, db_column="banos", null=True),
                ),
                (
                    "estacionamientos",
                    models.IntegerField(
                        blank=True, db_column="estacionamientos", null=True
                    ),
                ),
                (
                    "bodegas",
                    models.IntegerField(blank=True, db_column="bodegas", null=True),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, db_column="url", max_length=255, null=True
                    ),
                ),
                (
                    "latitud",
                    models.FloatField(blank=True, db_column="latitud", null=True),
                ),
                (
                    "longitud",
                    models.FloatField(blank=True, db_column="longitud", null=True),
                ),
                (
                    "uf_clp",
                    models.FloatField(blank=True, db_column="uf_clp", null=True),
                ),
            ],
            options={
                "verbose_name": "Venta",
                "verbose_name_plural": "Ventas",
                "db_table": "ventas",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="Property",
        ),
    ]
