# Generated by Django 5.2.5 on 2025-08-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="youtube_video_url",
            field=models.URLField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="URL del Video de YouTube",
            ),
        ),
    ]
