# Generated by Django 5.2.5 on 2025-08-19 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_property_youtube_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="properties/",
                verbose_name="Imagen de la Propiedad",
            ),
        ),
    ]
